apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: Aleksandar_Lazic
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: centos
  spec:
    dockerImageRepository: centos
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: Aleksandar_Lazic
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: haproxy-test
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: Aleksandar_Lazic
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: haproxy-test
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: haproxy-test:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/git001/haproxy.git
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
      type: Docker
    triggers:
    - github:
        secret: NAYWj7reurv5q2EVBEyU
      type: GitHub
    - generic:
        secret: USpK2sGw0tgxI08WFycA
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: Aleksandar_Lazic
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: haproxy-test
  spec:
    replicas: 1
    selector:
      app: haproxy-test
      deploymentconfig: haproxy-test
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: Aleksandar_Lazic
        creationTimestamp: null
        labels:
          app: haproxy-test
          deploymentconfig: haproxy-test
      spec:
        containers:
        - name: hx-socklog
          image: haproxy-test:latest
          command:
           - /usr/sbin/socklog
           - inet
           - "0"
           - $(SYSLOG_PORT)
          env:
          - name: SYSLOG_PORT
            value: "8514"
          ports:
          - containerPort: 8514
            protocol: UDP
        - name: haproxy-test
          image: haproxy-test:latest
          env:
          - name: HTTP_BIND_PORT
            value: "8080"
          - name: MONITOR_BIND_PORT
            value: "9120"
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - haproxy-test
        - hx-socklog
        from:
          kind: ImageStreamTag
          name: haproxy-test:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: Aleksandar_Lazic
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: haproxy-test
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8514-tcp
      port: 8514
      protocol: UDP
      targetPort: 8514
    selector:
      app: haproxy-test
      deploymentconfig: haproxy-test
  status:
    loadBalancer: {}
kind: List
metadata: {}
