apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: haproxy-test
    name: haproxy-test
  spec:
    replicas: 1
    selector:
      app: haproxy-test
      deploymentconfig: haproxy-test
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: haproxy-test
          deploymentconfig: haproxy-test
      spec:
        containers:
        - name: rsyslog
          image: haproxy-test:latest
          command:
            - /rsyslogd-wrapper.sh
          env:
            - name: SYSLOG_PORT
              value: "8514"
          ports:
          - containerPort: 8514
            protocol: UDP
        - env:
          - name: HTTP_BIND_PORT
            value: "8080"
          - name: MONITOR_BIND_PORT
            value: "9120"
          image: haproxy-test:latest
          ports:
          - containerPort: 8080
            protocol: TCP
            containerPort: 9120
            protocol: TCP
          imagePullPolicy: Always
          name: haproxy-test
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - haproxy-test
        from:
          kind: ImageStreamTag
          name: haproxy-test:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
